name: Lint

on: [push, pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          extensions: mbstring, intl
          tools: php-cs-fixer

      - name: Check PHP code style
        run: php-cs-fixer fix --dry-run --diff --rules=@PSR12 app/
